# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class CompaniesItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

class YCombinatorItem(scrapy.Item):
    # Define fields for your scraped data
    company_id = scrapy.Field()
    company_name = scrapy.Field()
    short_description = scrapy.Field()
    long_description = scrapy.Field()
    batch = scrapy.Field()
    status = scrapy.Field()
    tags = scrapy.Field()
    location = scrapy.Field()
    country = scrapy.Field()
    year_founded = scrapy.Field()
    num_founders = scrapy.Field()
    founders_names = scrapy.Field()
    team_size = scrapy.Field()
    website = scrapy.Field()
    cb_url = scrapy.Field()
    linkedin_url = scrapy.Field()
    
    # Define field for images
    image_urls = scrapy.Field()  # This will store the image URLs
    images = scrapy.Field()  # This will store the downloaded images (generated by the images pipeline)
